version: "3.1"

services:

  master:
    image: maneeshkumar/jmaster:latest
    tty: true
    ports:
      - "60000"
    networks:
      - mk
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      placement:
          constraints: [node.role == manager]
  slave:
    image: maneeshkumar/jserver:latest
    tty: true
    networks:
      - mk
    ports:
      - "50000"
      - "1099"
    deploy:
      #mode: global
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == worker]

  influxdb:
    image: maneeshkumar/influxdb:latest
    container_name: influxdb
    environment:
      - INFLUXDB_DB=jmeter
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - mk

  grafana:
    image: maneeshkumar/grafana:latest
    ports:
      - "3005:3000"
    depends_on:
      - influxdb
      - master
      - slave
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - mk

networks:
  mk:
